### PR TITLE
Use erl_lint to detect compile errors

### LINKED ISSUE #288: Should not pass on malformed expression.
Simple example, returns no error, even if there is a syntax error.

```erlang
-record(r, {
    integer :: integer()
}).

-spec incr(integer()) -> integer().
incr(I) -> I + 1.

-spec test() -> integer().
test() ->
    Record = #record{integer = 0},
    incr(Record.integer). % Should be Record#r.integer
```

### LINKED ISSUE #291: Missing included path and function signature being present or not.
```erlang
% include/test.hrl
-define(ZERO, 0).
```

```erlang
-module(test).

-include("test.hrl").

-spec test1(integer()) -> bool().
test1(I) -> test2(I).

-spec test2(integer()) -> bool().
test2(I) ->
    I < ?ZERO.
```

Depending on how you invoke gradualizer for this, you will get a success or not. The cases are like so:

| `-I include` | `-spec test2...` present | Result |
| - | - | - |
| True |  True | No error |
| True | False | No error |
| False |  True | No error |
| False | False | `Call to undefined function test2/1 on line 6 at column 13` |

Funny enough, if you check the output of `epp`, you see an error within the body of `test2` for the error case: makes sense, the macro `?ZERO` is undefined.

Does the error make sense? The function _IS_ defined in there but the body fails. There's no function signature anyway ... shouldn't we just expect `any()` anyway?

What's the best way to fix this?

### LINKED ISSUE #371: internal crash on comparison of unbound variable to non-contractive type
Given this code:

**Steps to repro**:

`./bin/gradualizer sample.erl`

where `sample.erl` contains:

```erl
-module(sample).

-type loop() :: loop().

-spec main(any()) -> loop().
main(ok) -> X.
```

**Actual behavior**

crash:

```
escript: exception error: bad key: 'X'
  in function  map_get/2
     called as map_get('X',#{})
     *** argument 1: not present in map
  in call from typechecker:do_type_check_expr_in/3 (src/typechecker.erl, line 2248)
  in call from typechecker:type_check_expr_in/3 (src/typechecker.erl, line 2241)
  in call from typechecker:check_clause/5 (src/typechecker.erl, line 3443)
  in call from typechecker:'-check_clauses/5-fun-0-'/5 (src/typechecker.erl, line 3400)
  in call from lists:foldl/3 (lists.erl, line 1285)
  in call from typechecker:check_clauses/5 (src/typechecker.erl, line 3398)
  in call from typechecker:check_clauses_fun/3 (src/typechecker.erl, line 3372)
  ```

**Expected behavior**

The same as for the example above with `-type loop() :: any()`:

```
sample.erl: Unknown variable 'X' on line 6 at column 13.
```

I doubt this kind of thing comes up much in the wild, I found it playing around with intentionally weird code using recursive types.

### PR DESCRIPTION
**Pull request by zuiderkwast**
When checking `.erl` files, use `erl_lint` to detect compile errors. This is basically what the `basic_validation` compiler pass does.

It detects use of undefined variables, undefined functions, undefined records, missing include files and some things you could expect the parser to detect such as `foo() -> ok; bar() ->ok.` (Note the semicolon.) and `f(X + 1) -> X.`.

This pass is not used when checking beam files, since we already know that this abstract form compiles.

Fixes #291. Fixes #288. Fixes #371.

### CODE REVIEW

**Comment by zuiderkwast** [comment]
For reviewers: Tests for the lint errors are moved to a separate module, because if there are lint errors, we don't run the type checker and thus we don't detect non-lint errors in the same module. With one module for lint errors (e.g. undefined local type) and another for type errors (e.g. undefined remote type) we cover all of them.

File: src/gradualizer.erl [hunk 1]
```diff
@@ -56,21 +56,47 @@ type_check_file(File) ->
...
+            end;
+        ".beam" ->
+            case gradualizer_file_utils:get_forms_from_beam(File) of
+                {ok, Forms} ->
+                    type_check_forms(File, Forms, Opts);
+                Error ->
+                    throw(Error) % TODO: Don't use throw. These are user errors.
+            end;
+        Ext ->
+            throw({unknown_file_extension, Ext}) %% TODO: Don't use throw here.
```
Comment (josefs) [inline src/gradualizer.erl:76]: Can you create a ticket and add the ticket number to the TODOs so that we keep track of that we need to remove the throws in the future?

**Review by josefs — APPROVED** [review]
Thanks. I like changes that remove code. 
The thing that makes me a little uneasy about this is the performance implications of this change. We're adding a whole extra traversal over the AST. But on the other hand, we haven't really cared much about the performance of Gradualizer yet and I haven't gotten any feedback that it's slow.

File: test/misc/lint_errors.erl [hunk 2]
```diff
@@ -0,0 +1,43 @@
+%% This module doesn't even compile. There errors here are caught by erl_lint.
```
Comment (erszcz) [inline test/misc/lint_errors.erl:1]:
```suggestion
%% This module doesn't even compile. The errors here are caught by erl_lint.
```

**Review by erszcz — APPROVED** [review]
Looks good to me!

File: src/gradualizer.erl (hunk 1 above)
Comment (zuiderkwast) [reply src/gradualizer.erl]: Too much effort to describe it, including context and consequences, in an issue. I deleted the TODOs instead.

**Comment by zuiderkwast** [comment]
> We're adding a whole extra traversal over the AST. But on the other hand, we haven't really cared much about the performance of Gradualizer yet and I haven't gotten any feedback that it's slow.

We have had performance issues and even infinite loops, so we have added hacks to limit the depth of certain things.

I think this pass is very quick (linear maybe), besides it can be regarded as parser post-processing and we do use the lexer, preprocessor and parser passes already.

Good that it's accepted. Now we closed a number of issues. :-)
