### PR TITLE
Fix var binds in guard sequences

### LINKED ISSUE #531: Crash with `Uncaught error: {case_clause, ..` in `typechecker:do_type_check_expr/2`
A repro:

```erlang
-module(gradualizer_repro2).

-export([foo/2]).

-spec foo(List1, List2) -> List2 when
  List1 :: [Int],
  List2 :: [Int|{Int,Int}],
  Int :: integer().
foo([], Acc) ->
  Acc;
foo([H | T], []) ->
  foo(T, [H]);
foo([H | T], [HA | TA]) when is_integer(HA), H == HA + 1 ->
  foo(T, [{HA, H} | TA]);
foo([H | T], [{HAB, HAE} | TA]) when H == HAE + 1 ->
  foo(T, [{HAB, H} | TA]);
foo([H | T], Acc) ->
  foo(T, [H | Acc]).
```

```
===> Uncaught error: {case_clause,#{'HA' => {type,0,integer,[]}}}
===> Stack trace to the error location:
[{typechecker,do_type_check_expr,2,
              [{file,"/Users/ilyaklyuchnikov/code/gr-rebar3/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,1695}]},
 {typechecker,type_check_expr,2,
              [{file,"/Users/ilyaklyuchnikov/code/gr-rebar3/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,1687}]},
 {typechecker,type_check_rel_op,5,
              [{file,"/Users/ilyaklyuchnikov/code/gr-rebar3/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,2199}]},
 {typechecker,type_check_expr,2,
              [{file,"/Users/ilyaklyuchnikov/code/gr-rebar3/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,1687}]},
 {typechecker,check_guard_expression,2,
              [{file,"/Users/ilyaklyuchnikov/code/gr-rebar3/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,4613}]},
 {typechecker,'-check_guard/2-fun-0-',2,
              [{file,"/Users/ilyaklyuchnikov/code/gr-rebar3/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,4620}]},
 {lists,foldl_1,3,[{file,"lists.erl"},{line,1355}]},
 {typechecker,check_guard,2,
              [{file,"/Users/ilyaklyuchnikov/code/gr-rebar3/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,4619}]}]
```

### PR DESCRIPTION
**Pull request by erszcz**
Fix #531.

### CODE REVIEW

File: src/typechecker.erl [hunk 1]
```diff
@@ -4617,8 +4617,14 @@ check_guard_expression(Env, Guard) ->
...
-                             Ne = check_guard_expression(E, Guard),
-                             union_var_binds([Ne], E)
+                             NEnv = check_guard_expression(E, Guard),
+                             %% This is somewhat tricky.
+                             %% check_guard_expression/2 will return an env with just
+                             %% the types of vars used in the guard expression - we want these to
+                             %% override any types previously in the env.
+                             %% We still want to keep types of vars not used in the guard expression,
+                             %% though, so we pass both NEnv and E to union_var_binds/2.
+                             union_var_binds([NEnv, E], E)
```
Comment (zuiderkwast) [inline src/typechecker.erl:4627]: Does this override the type or use glb or lub if the same variable is in both envs?

Comment (erszcz) [reply src/typechecker.erl:4627]: `union_var_binds` does GLB on the 1st argument, so the original type info from the spec is also taken into account.

Comment (zuiderkwast) [reply src/typechecker.erl:4627]: so maybe say "refine" instead of "override"?
